apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.gateway.name }}'
  namespace: '{{ .Values.namespace }}' 
spec:
  gatewayClassName: '{{ .Values.gatewayclass.name }}'
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
